### ISSUE TITLE
StreamInput Overview

### ISSUE THREAD

**Issue by sadiuk** [Devsh-Graphics-Programming/Nabla#110]
# Description
This issue covers features of the StreamInput future API. 
**Note:** currently there is no info on how all these features will look like in the actual API (spec should be released in the next 12 months).

## Overview 
 
There are 3 main capability groups:
1) Regular input control (keyboard, touchscreen etc).
2) Sensor processing (Gyro, accelerometer, compass etc).
3) Gesture and motion detection (Depth cameras).

OS-agnostic API. Some input devices support will be added via Khronos extensions.

Sensor processing capabilities:
1) Sensor-agnostic input. Different devices have different sensors that provide the needed input, so the API allows developers abstract from low-level device-specific stuff and focus on the input itself.
2) Handles almost eny sensors:
 - Multi-axis motion/position sensors, capacitive multi-touch surfaces.
 - RGB and Depth sensing cameras – including mono and stereo.
 - Microphone arrays for speech recognition etc.
 - Haptic devices, Biometric sensors etc.
 - etc.

The API is going to be graph-based: each input device is a separate node, and a combination of the input devices is a new kind of node - Filter Node. An app can access both high-level filter nodes and low-level device nodes.
A Filter Node can include image-processing (Can use APIs such as OpenCL and OpenMAX and receive data from external media frameworks).

## That's it
This is literally the only data i managed to dig up about StreamInput. It doesn't even have a wikipedia page XD. Everything is taken from [The Khronos StreamInput Overview Page](https://www.khronos.org/streaminput).

**Comment by devshgraphicsprogramming** [comment]
Why is SteamInput a Khronos thing?

**Comment by sadiuk** [comment]
> Why is SteamInput a Khronos thing?

Yeah, it is. And it's still in development

**Comment by sadiuk** [comment]
Looks like it's gonna be an awesome api that handles any possible input.
