### ISSUE TITLE
Next Path Tracing Sprint

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#131]
## Ditt Features
- [x] Commandline renderserver mode (render into EXR with set number of samples)
- [ ] Self-Intersection robust ray origins
- [x] Control camera speed (add it to the scene description)
- [x] Normal Map Support
- [x] Derivative Map scaling
- [x] Optimize sequence to fit RGB21_UINT, reorganise for locality, finish scramble advancement
- [x] Read max path depth from integrator, apply Russian Roulette
- [ ] Resize the window after loading the scene so it is less than the desktop size, but also the correct aspect ratio

## Extra Technical Features
- [ ] Lower raster frequency than raytrace (draw every Nth frame, allow different primary sample counts to continuations)
- [ ] MIS
- [x] Envmap support
- [x] Autoexposure
- [x] Tonemapping
- [ ] NEE
- [x] Single BLAS and pretransformed vertices for non-instanced meshes (encode the draw+triangle ID into the indexbuffer value)
- [ ] Heuristics for "deinstancing" meshbuffers (decide when it makes sense to pay double VRAM for positions and normals vs
- [ ] Both Blooms

## Sprint 2
- [x] Render multiple cameras when acting as a renderserver
- [x] GPU "bake" albedo textures for all materials
- [ ] Multi-monitor VR-Cave mode
- [ ] Optimize normal vertex attribute presence across all loaders in the engine
- [x] Render in four passes, with and without UVs (separate the vbuffer into bary+triID and bary deriv)
- [x] Occlusion Culling by @Przemog1 
- [ ] Support Opacity maps when constructing the vis buffer (stochastic alpha testing ;) )
- [x] Propagation rules in (or derived from) materials for AoVs
- [ ] Denoiser re-integration
- [ ] Fractional spp rendering, and control over spp per frame
- [ ] RGB21_USCALED position encoding?

## Sprint 3
- [ ] Compute OBBs for lights
- [ ] Schussler et. al Normalmaps and smooth shading normals
- [ ] NEE++
- [ ] Firefly rejection
- [ ] Temporal denoiser
- [ ] Cache and HTTP download models and textures
- [ ] GPU assisted asset manipulation
- [ ] Runtime GUI for adjustments

## Vulkan
- [ ] Drag&Drop scenes
- [ ] Use anyhit for stochastic transparency

**Comment by devshgraphicsprogramming** [comment]
# Next Release

## Bugfixes
- [ ] Bumpmapping #260 (assign @devshgraphicsprogramming )
- [ ] Weird geometry randomly appearing #260  (assign @devshgraphicsprogramming )
- [ ] Window sometimes freezes/becomes unresponsive after loosing focus
- [ ] Bad Truncated Gaussian distribution causing "double vision"
- [ ] Respect or fix up the near and far plane settings
- [ ] Conformance test (a batch file that causes all scenes to be rendered and denoised, then compare results)
- [ ] Camera Y look and X move axes being inverted sometimes

## Features
- [ ] Being able to quit at any time
- [ ] Being able to "free" (move) the camera away from any view (therefore interrupting the fixed spp rendering for that view)
- [ ] Envmap/HDRI support
- [ ] Optimize sequence to fit RGB21_UINT, reorganise for locality, finish scramble advancement (assign @devshgraphicsprogramming )
- [ ] Read max path depth from integrator, apply Russian Roulette (assign @devshgraphicsprogramming )
- [ ] XML sensor tags for camera look and zoom speed

**Comment by Erfan-Ahmadi** [comment]
> Being able to "free" (move) the camera away from any view (therefore interrupting the fixed spp rendering for that view)
use 'END' Key to skip rendering of current sensor to file (screenshots)
>  Being able to quit at any time
use `Q` to quit everything (while rendering to file or interacting with camera)
>  Camera Y look and X move axes being inverted sometimes
fixed and tested on 2 scenes with different handedness
> Respect or fix up the near and far plane settings
taken straight from mitsuba but added log if depth range is too big
>  Window sometimes freezes/becomes unresponsive after loosing focus
Added `device->run()` in screenshoting while loop, should probably fix this. (Tested on my own windows 10 and alt+tab works)

**Comment by devshgraphicsprogramming** [comment]
> Added device->run() in screenshoting while loop, should probably fix this. (Tested on my own windows 10 and alt+tab works)

ah yeah old/dumb irrlicht needs that every frame to get events (mouse, keypresses, titlebar setting etc) to the window.

There's also a begin/end scene from `driver` that is necessary to do a swapchain buffer swap (make sure image updates).

**Comment by devshgraphicsprogramming** [comment]
I just need to repeat the work I've done for normalmaps with bumpmaps
