### ISSUE TITLE
Libjpeg-turbo support?

### ISSUE THREAD

**Issue by AnastaZIuk** [Devsh-Graphics-Programming/Nabla#135]
we could consider using this one instead of current libjpeg

**Comment by Crisspl** [comment]
It's extremely easy, turbo has exactly the same API so it's a matter of changing include dir and lib being linked. What's more difficult is integrating it into our build system, I tried doing this like 2 years ago but you cant really use `add_subdirectory` for that, ExternalProject is needed. I guess it shouldnt be a problem for you though

**Comment by AnastaZIuk** [comment]
well in that case I can upgrade it

**Comment by AnastaZIuk** [comment]
@devshgraphicsprogramming?

**Comment by devshgraphicsprogramming** [comment]
make it work with `add_subdirectory` ;)

**Comment by AnastaZIuk** [comment]
@devshgraphicsprogramming as you wish

**Comment by Crisspl** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo/issues/353

**Comment by AnastaZIuk** [comment]
in that case there is a problem, but I will check it for fun

**Comment by AnastaZIuk** [comment]
or I can patch their cmake XD

**Comment by AnastaZIuk** [comment]
but we should not consider this option at the moment

**Comment by AnastaZIuk** [comment]
@Crisspl @devshgraphicsprogramming well, it's curious but I'm able to attach it via `add_subdirectory` using their master branch and build it in generated solution. It means we can remove our jpeg library and replace it all with this one.

**Comment by Crisspl** [comment]
Maybe something changed until then, good for us

**Comment by AnastaZIuk** [comment]
> Maybe something changed until then, good for us

yeah, patched https://github.com/Devsh-Graphics-Programming/Nabla/issues/135#issuecomment-877436713
