### ISSUE TITLE
Make Nabla build as shared library, change the default cmake config to shared lib

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#143]
## Description
Shared libs config for Win32, Linux and Android.

## Description of the related problem

Currently builds of Nabla incl. samples can be in excess of 50 GB, using .dll could cut it down by an order of magnitude,

## Solution proposal

Produce 1 .dll/.so per namespace (also split up the static libs like this).

Dependencies are still to be linked statically into Nabla namespace libs (don't want DLL hell).

## Additional context

To complete after appsincadd contract is finalized.

**Comment by AnastaZIuk** [comment]
should there be a CMake switch between static/shared?

**Comment by devshgraphicsprogramming** [comment]
> should there be a CMake switch between static/shared?

I believe CMake already has this option, we just need to respect it.

**Comment by AnastaZIuk** [comment]
> Produce 1 .dll/.so per namespace (also split up the static libs like this).

Could you describe it a little more?

**Comment by devshgraphicsprogramming** [comment]
this is the old DLL/so issue
https://github.com/buildaworldnet/IrrlichtBAW/issues/91

that's the 6-lib old part
https://github.com/buildaworldnet/IrrlichtBAW/issues/196

**Comment by devshgraphicsprogramming** [comment]
getting done (at least on Windows)
