### ISSUE TITLE
Deduce OpenGL VSync modes from Swapchain Presentation modes

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#145]
## Description
`extGlSwapInterval(-1)` used to be called in the engine at OpenGL initialization, now nothing is chosen at all.

## Solution proposal
Call `extGlSwapInterval` with the following values:
- `1` total VSync (when `VK_PRESENT_MODE_FIFO_KHR` is present)
- `0` no VSync (probably `VK_PRESENT_MODE_IMMEDIATE_KHR` or `MAILBOX`, I believe this depends on double buffering or not)
- `-1` if late then tear (when `VK_PRESENT_MODE_FIFO_RELAXED_KHR` is present)

**Comment by Crisspl** [comment]
What does `-1` do?

**Comment by devshgraphicsprogramming** [comment]
> What does `-1` do?

Sync but if late then tear

Basically you VSync if you're going above display refresh rate, but tear if you're not (if a new frame arrives before the next refresh, it waits in the queue for the refresh, if it arrived after then it gets presented immediately).

**Comment by achalpandeyy** [comment]
Done in #160
