### ISSUE TITLE
generated Nabla.h doesn't update

### ISSUE THREAD

**Issue by AnastaZIuk** [Devsh-Graphics-Programming/Nabla#168]
TODO for me
@Erfan-Ahmadi please describe the problem here

**Comment by devshgraphicsprogramming** [comment]
I saw that too, if I modify `nabla.h.in` the generated `nabla.h` doesnt get regenerated

**Comment by devshgraphicsprogramming** [comment]
BuildConfig/options header doesn't seem to update after cmake option change either

**Comment by devshgraphicsprogramming** [comment]
there is no generated `nabla.h.in` only `nabla.h`

we edit `nabla.h.in` in source dir/include

**Comment by devshgraphicsprogramming** [comment]
why is there a generated `nabla.h.in` ?

all I should have is just `nabla.h.in` in source dir and generated `nabla.h` in build dir/config

**Comment by AnastaZIuk** [comment]
the key is that we inject code, so the finall `nabla.h.in` is `wrapped code` + input `nabla.h.in` (in include), then we perform configure on it to generate `nabla.h`

**Comment by devshgraphicsprogramming** [comment]
how many `nabla.h` ARE THERE!?

**Comment by AnastaZIuk** [comment]
only one

**Comment by devshgraphicsprogramming** [comment]
how many `nabla.h.in`!?

**Comment by AnastaZIuk** [comment]
2, one generated in build and one from include (the one you should modify in include)

**Comment by devshgraphicsprogramming** [comment]
can we have only 1 ?

**Comment by AnastaZIuk** [comment]
no because it doesn't make any sense to use `nabla.h.in` then, you don't want to inject wrapped code into commited `include/nabla.h.in`

**Comment by AnastaZIuk** [comment]
I can get rid of `nabla.h.in` at all if you want (though find it good as it is) but if we wanted to use `nabla.h.in` there must be also a generated one in build

**Comment by devshgraphicsprogramming** [comment]
I just tested removing `#include "ICursorControl.h"` from `nabla.h.in` on `input_channel_demo` branch, does not update the generated files!

**Comment by devshgraphicsprogramming** [comment]
Seems done
