### ISSUE TITLE
Issues with building on Manjaro

### ISSUE THREAD

**Issue by tree786** [Devsh-Graphics-Programming/Nabla#198]
Hallo

I am coming from stock Irrlicht, and wanted to check this framework out. I have tried to build it on Manjaro , following git cloning the repo and following build commands:
```
cd Nabla
mkdir build
cd build 
cmake ..
make
```
However it seem to fail giving me this error message (after 6% building complete):
```
  File "/home/../Desktop/nabla/Nabla/src/nbl/builtin/builtinHeaderGen.py", line 21, in <module>
    outp = open(outputFilename,"w+")
FileNotFoundError: [Errno 2] No such file or directory: '/home/../Desktop/nabla/Nabla/build/include/nbl/builtin/builtinResources.h'
make[2]: *** [src/nbl/CMakeFiles/builtin_resources.dir/build.make:191: include/nbl/builtin/builtinResources.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:5972: src/nbl/CMakeFiles/builtin_resources.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```
I have no idea how to fix this, or what i am missing . Is it a dependency i need? My plans are to try and use nabla as a submodule rendering framework.

Gracias

**Comment by devshgraphicsprogramming** [comment]
Our intern is working on an X11 implementation
https://github.com/Devsh-Graphics-Programming/Nabla/pull/187

watch his branch, he "should" be done by end-of September.
