### ISSUE TITLE
Image Format Promotion

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#250]
## Description
Format Promotion for image formats not supported in hardware.
Involved: @achalpandeyy @devshgraphicsprogramming @Erfan-Ahmadi 

## Rules for promotion:
1. we dont have a transcoder of block compressed formats, so you cannot promote to a compressed format
2. aspects must be preserved or added (changing depth or stencil into depth+stencil format is ok)
3. channel count must be preserved or increased
4. data range must be preserved or expanded in each channel
5. data precision must be preserved or improved in each channel (this usually means bit-depth when comparing non SRGB formats)
6. when there are multiple matches, you must choose the one with the smallest texel block
P.S. You need to be careful with usages, i.e. no storage image supports SRGB, but we usually get around that by creating UINT views and manually encoding.

## Converstation

> Erfan: Why not promote in the beginning of ICPUImage conversion instead of only promoting the ones used in ImageViews...

> Devsh: But the usage support sometimes depends on the views format

> Achal: Won't this promote the duplicated ones as well?
Ideally you want to put it after the elimateDuplicate calls
What is the point of first promoting then trashing the image?

**Comment by devshgraphicsprogramming** [comment]
OK, so far we've agreed with @Erfan-Ahmadi to extend the `IUtilities` class with being able to upload regions to a texture while converting the format at the same time.

This will give us really easy texture format promotion.

The CPU2GPU converter will just need to decide whether and format to promote the `ICPUImage` and `ICPUImageView`

**Comment by devshgraphicsprogramming** [comment]
but for any work on format promotion to start, @achalpandeyy needs to finish the format usage support reporting from `IPhysicalDevice`

**Comment by devshgraphicsprogramming** [comment]
Supposedly finished
```cpp
        virtual const SFormatImageUsage& getImageFormatUsagesLinear(const asset::E_FORMAT format) = 0;
        virtual const SFormatImageUsage& getImageFormatUsagesOptimal(const asset::E_FORMAT format) = 0;
        virtual const SFormatBufferUsage& getBufferFormatUsages(const asset::E_FORMAT format) = 0;
 ```
 
 @achalpandeyy tell us of any remaining TODOs

**Comment by achalpandeyy** [comment]
- Works on the Vulkan backend
- On GLES backend, https://github.com/Devsh-Graphics-Programming/Nabla/pull/160#discussion_r748727832 needs to be solved --which will lead you to caching properties for all the formats upfront (as was discussed on Discord)
- Not implemented on the GL backend

**Comment by devshgraphicsprogramming** [comment]
> data precision must be preserved or improved in each channel (this usually means bit-depth when comparing non SRGB formats)

Fortunately for formats which do not have constant precision (SRGB and variants of Float) the precision is largest near 0, so compare precision there.

**Comment by devshgraphicsprogramming** [comment]
> On GLES backend, https://github.com/Devsh-Graphics-Programming/Nabla/pull/160#discussion_r748727832 needs to be solved --which will lead you to caching properties for all the formats upfront (as was discussed on Discord)On GLES backend, https://github.com/Devsh-Graphics-Programming/Nabla/pull/160#discussion_r748727832 needs to be solved --which will lead you to caching properties for all the formats upfront (as was discussed on Discord)


Not only does this need to get done, but [also this.](https://github.com/Devsh-Graphics-Programming/Nabla/pull/357#issuecomment-1158094820)
