### ISSUE TITLE
pathtracer strange double texture in scene and missing bump

### ISSUE THREAD

**Issue by YoranBosman** [Devsh-Graphics-Programming/Nabla#260]
## Describe the bug
- bump missing from floor
- strange textured ball in scene
![image](https://user-images.githubusercontent.com/15725984/141364849-3a8b149c-e7b9-4c30-9e5a-7b03da6a0b0e.png)

## Steps to Reproduce
https://drive.google.com/file/d/1f4_ZrripgDxeXmH3vjoLCR30BXkrFIVa/view?usp=sharing
open in pathtracer

## Expected vs observed behavior
see mitsubareference.jpg in zip

**Comment by devshgraphicsprogramming** [comment]
![image](https://user-images.githubusercontent.com/6894321/144718149-e2920718-435e-44c1-b20c-4134d23f43af.png)
fixed
