### ISSUE TITLE
Stop overwriting CMake internals/reading variables

### ISSUE THREAD

**Issue by AnastaZIuk** [Devsh-Graphics-Programming/Nabla#268]
it may lead to unstable behaviours on certain CMake versions, just see https://github.com/Devsh-Graphics-Programming/Nabla/blob/criss_baw/cmake/common.cmake#L309

We should not have changed variables that are only being used for reading target property, e.g. `TARGET_NAME` like above

**Comment by devshgraphicsprogramming** [comment]
Might be related:
https://github.com/buildaworldnet/IrrlichtBAW/issues/311
https://github.com/buildaworldnet/IrrlichtBAW/issues/298

**Comment by devshgraphicsprogramming** [comment]
Did your recent work fix any of this @AnastaZIuk ?

**Comment by AnastaZIuk** [comment]
> Did your recent work fix any of this @AnastaZIuk ?

I think most of those issues are fixed
