### ISSUE TITLE
Swapchains and surfaces

### ISSUE THREAD

**Issue by Crisspl** [Devsh-Graphics-Programming/Nabla#29]
### What's happening in Vulkan
Swapchain is created from surface and other params like minImageCount. Swapchain images can be gathered from the swapchain. Then we're creating as many FBOs as there are images (and obvs attaching one image to each) and render to an fbo of number queried from `vkAcquireNextImageKHR`

### What's happening in OpenGL
No direct access to swapchain images, no explicit swapchain actually. In SDL2 double-buffering and swapping is done with a single call (`SDL_Flip(surface)` or `SDL_RenderPresent(renderer)` -- not sure, Magnum uses SDL_Flip but SDL2 migration guide says it's been replaced with SDL_RenderPresent, however i dont know what is that renderer yet)
https://wiki.libsdl.org/MigrationGuide
https://github.com/mosra/magnum/blob/master/src/Magnum/Platform/Sdl2Application.cpp#L439

### Conclusion
Swapchain and surface have to be one thing in our API.
OpenGL impl should be pretty straight forward then, however...
On Vulkan.. Swapchain/Surface API cannot expose images because in you OpenGL cannot do this. So: 
A) do under-the-hood blits into swapchian images in Vulkan, or 
B) make Swapchain/Surface API expose images, so that things are getting easy in Vulkan, but in OpenGL we're doing under-the-hood blits into default framebuffer (seems like much better option tbh)

Anyway seems like Swapchain and Surface need to get together into a single interface

**Comment by devshgraphicsprogramming** [comment]
> No direct access to swapchain images, no explicit swapchain actually. 

This is why we have to emulate!

our OpenGL "swapchain" should create `minImageCount` worth of `COpenGLImage`

Then the surface will "flip" these "fake" swapchain images to the implicit one

> Swapchain and surface have to be one thing in our API.

Because the above is possible, I do not concur.

> but in OpenGL we're doing under-the-hood blits into default framebuffer (seems like much better option tbh)

Yees this is what we want

> Anyway seems like Swapchain and Surface need to get together into a single interface

No we dont want that :(

**Comment by devshgraphicsprogramming** [comment]
the actual design of #28 is much different from this issue's design proposal, so closing issue to avoid confusion
