### ISSUE TITLE
NewAPI Fixes and Changes

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#305]
Here are the suggested changes to make to the NewAPI:

- [ ] Move CommandBuffer Allocation/Free from LogicalDevice to CommandPool

These changes affect most of the examples and will touch many places, they should come after most of the branches are synced together and trivial issues is fixed.

**Comment by devshgraphicsprogramming** [comment]
> Here are the suggested changes to make to the NewAPI:
> 
> * [ ]  Move CommandBuffer Allocation/Free from LogicalDevice to CommandPool
> 
> These changes affect most of the examples and will touch many places, they should come after most of the branches are synced together and trivial issues is fixed.

seems that this one can be done by @achalpandeyy
