### ISSUE TITLE
 CCW/CW face orientation is wrong

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#308]
## Describe the bug
 CCW and CW swapped around
We do `glClipControl(GL_UPPER_LEFT, GL_ZERO_TO_ONE)` which has the effect of flipping the winding order

## Steps to Reproduce
MeshLoaders Example

**Comment by devshgraphicsprogramming** [comment]
Idea for a test.

# 1
Write some sort of a clear mathematical gradient/image defined as a function `f(x,y)` (the toy path tracer in compute is actually good enough).

# 2
```glsl
imageStore(swapchainImage,ivec2(x,y),vec4(f(x,y),1.f))
```

# 3
Should yield identical images in Renderdoc debug (if not, find out why).

# 4
Then find out if presenting the swapchain on Vulkan flips the image compared to Renderdoc debug.

# 5
Then come up with a way to make OpenGL present behave same way as Vulkan.
