### ISSUE TITLE
Command Pool Reset

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#373]
- [x] Add Atomic Reset Counter to Command Pool + cached counter in CommandBuffer
- [x] CommandBuffer::CheckForCommandPoolReset function

Command buffer Pool's atomic counter and if it was higher than it's cached value, it will change state to the "initial state"

Sane people don't reset command pool while recording command buffer so no need to CheckForCommandPoolReset in every function for now, but add later

Command Buffer

```c
public:
bool reset(flag)
{
  if (!canReset etc)
    return false;
  if(flag.hasValue(RELEASE_RESOURCES_BIT))
    releaseResourcesBackToPool(m_pool);
  resetCommon();
  return true;
}

protected:

uint32_t cachedPoolResetStamp = 0u;
inline bool checkForCommandPoolReset()
{
  if (m_pool->getResetCounter()<=cachedPoolResetStamp)
    return false;

  // no need to releaseResourcesBackToPool(m_pool); because pool already has claimed it's resources
  resetCommon();
  return true;
}
inline virtual void resetCommon()
{
  cachedPoolResetStamp = m_pool->getResetCounter();
}
```

**Comment by devshgraphicsprogramming** [comment]
still not implemented https://github.com/Devsh-Graphics-Programming/Nabla/pull/345/files#r1040787374

**Comment by devshgraphicsprogramming** [comment]
done
