### ISSUE TITLE
Bump Minimum required Vulkan version to 1.2

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#377]
## Description
Vulkan 1.2 introduces nice features and promotes a lot of cool extensions to core.

## Description of the related problem
There is a concern about what GPUs we're leaving behind which only support Vk 1.1

## Solution proposal
Find a better source of Vulkan device capability reports than `vulkan.gpuinfo.org`.

## Additional context
Most Android phones seem to be stuck at 1.1, so does MoltenVK (but soon it will hit 1.2)

**Comment by Erfan-Ahmadi** [comment]
https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml

**Comment by Erfan-Ahmadi** [comment]
> Can bump to 1.3 as we learnt at Vulkanized 2023
Can you explain more?

**Comment by devshgraphicsprogramming** [comment]
> > Can bump to 1.3 as we learnt at Vulkanized 2023
> > Can you explain more?

Unfortunately the video of the talk given by
```
Vulkan on Android by Alon Or-bach, Google.
Video Pending | Slides Pending 
```
they're probably editing out my inflammatory question about ChromeOS

But in that talk there was some info that Android 13 semi-requires Vk 1.3 and BDA.

Also Molten VK is almost at 1.2 and working on 1.3
> Vulkan 1.2 + extns CTS: 322K pass, 10K fail (3.2%)

**Comment by devshgraphicsprogramming** [comment]
Approved, just need to find time to do it.
