### ISSUE TITLE
`CWindowAndroid` is a mess and needs fixing

### ISSUE THREAD

**Issue by AnastaZIuk** [Devsh-Graphics-Programming/Nabla#382]
TODOs:

- fix https://github.com/Devsh-Graphics-Programming/Nabla/blob/window_resizing/include/nbl/ui/CWindowAndroid.h#L33 otherwise it crashes when `getManager` is invoked
- better class hermetization, why we have stuff that should not be available by user placed in public section?

**Comment by devshgraphicsprogramming** [comment]
Examples/Engine doesn't need to run, just needs to compile.

We wont do any testing with running samples until we can get a hand on a Vulkan 1.1 x86 Android device.

**Comment by devshgraphicsprogramming** [comment]
screw android (for now)
