### ISSUE TITLE
Requiring KHR_synchronization2

### ISSUE THREAD

**Issue by deprilula28** [Devsh-Graphics-Programming/Nabla#384]
## Description
Eventually we should require `KHR_synchronization2` support, due to adding new stage flags beyond the 32-bit limit of the current bitmask:
> It also adds new pipeline stage and access flag types that extend into the 64-bit range, as we have run out within the 32-bit range.

Our Barrier API would need to change to account for this. The blocker is that currently, there is [really poor coverage of VK 1.1 and 1.2 devices](https://vulkan.gpuinfo.org/listfeaturesextensions.php?extension=VK_KHR_synchronization2&platform=all).

(Original comment on #357)

**Comment by devshgraphicsprogramming** [comment]
Related https://github.com/Devsh-Graphics-Programming/Nabla/issues/377#issuecomment-1176623603

Maybe we should wait till the next release of MoltenVK to see what's available.

And this is useful to keep an eye on
https://github.com/KhronosGroup/Vulkan-Profiles/blob/master/profiles/VP_ANDROID_baseline_2021.json

**Comment by devshgraphicsprogramming** [comment]
Approved for the next rework of sync stuff

**Comment by devshgraphicsprogramming** [comment]
done.
