### ISSUE TITLE
CommandBuffer::Begin needs to release resources

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#407]
CommandBuffer::Begin doesn't act like CommandBuffer::Reset when the command pool is created with the RESET_COMMAND_BUFFER flag. It's not a matter of Vulkan API calls, it's a matter of releasing the references that command buffer holds onto in our internal command buffer implementation.

To reproduce: https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/commit/11748d017d9e9ffe84414ccb0ab7169109d28f4b

**Comment by devshgraphicsprogramming** [comment]
A little bit of context, I think that right now the OpenGL commandbuffer will hold onto the images while the Vulkan one will not :D

**Comment by devshgraphicsprogramming** [comment]
@achalpandeyy make sure to do one commit on your branch with message `Fix #407` then this issue will autoclose after I approve the PR

**Comment by achalpandeyy** [comment]
Done here https://github.com/Devsh-Graphics-Programming/Nabla/pull/345/commits/06f524ff0a0ac757e7a190735f47aac5dc940d83
