### ISSUE TITLE
Unify PCH of examples

### ISSUE THREAD

**Issue by AnastaZIuk** [Devsh-Graphics-Programming/Nabla#419]
the reason for that is examples_tests' build directory takes more then 69 GB when compiled with all of samples because of huge PCHs generated for each, it's not good for our CI by the way

**Comment by devshgraphicsprogramming** [comment]
This has highest priority now

**Comment by AnastaZIuk** [comment]
[resolved ](https://github.com/Devsh-Graphics-Programming/Nabla/commit/509b21df78a2294530dcd3345fa47c2bf773b7c1)
