### ISSUE TITLE
Extensions should declare what device features they require/prefer to be enabled

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#424]
## Description
Here are some classes that function differently based on which device features are enabled:
`ICullingLoDSelectionSystem` => multiDrawIndirect, drawIndirectCount
`CDrawIndirectAllocator` => drawIndirectCount
`CSubpassKiln` => multiDrawIndirect, drawIndirectCount

Each of these classes should have static methods with similar signature:
```cpp
static void enablePreferredFeautres(const SPhysicalDeviceFeatures& availableFeatures, SPhysicalDeviceFeatures& features)
{
    features.multiDrawIndirect = availableFeatures.multiDrawIndirect;
    features.drawIndirectCount = availableFeatures.drawIndirectCount;
}
static void enableRequiredFeautres(SPhysicalDeviceFeatures& features)
{
    features.somethingElse = true;
}
```
this function is static and can't be virtual and inherited from a base class.

Currently 99% of examples use common api and don't have access to "availableFeatures" that gets retrieved from PhysicalDevice

TODO: Implement solution in CommonAPI that considers the need of extension/utilities for device feature.

Solution1: PhysicalDeviceSelector "select" function also takes the `SPhysicalDeviceFeatures& featuresToEnable` and edits that when selecting a physical device, then the user can override that function and request "more" extensions based on the physical device it chose, or a new function in `class PhysicalDeviceSelector` 

Solution2: CommonAPI takes optionalFeaturesToEnable as another `SPhysicalDeviceFeatures` and somehow merges them into `DeviceCreateParams::featuresToEnable` if they are available

**Comment by devshgraphicsprogramming** [comment]
Define a C++20 concept called `nbl::ext::Extension` at the end of `nabla.h` that requires these static methods to be present.

Then use a variadic template function in CommonAPI
```cpp
template<ext::Extension... extensions_t>
```
and somewhere inside apply a parameter pack expression to apply the features
```cpp
(extensions_t::enableRequiredFeatures(features), ...);
(extensions_t::enablePreferredFeautres(availableFeatures,features), ...);
```

**Comment by devshgraphicsprogramming** [comment]
Give up on automagically selecting the "best" device, unless there's a way to take a user supplied lambda for comparing two devices and there's a compile-time way to ensure the operator yields a strict ordering.

**Comment by Erfan-Ahmadi** [comment]
> Define a C++20 concept called `nbl::ext::Extension` at the end of `nabla.h` that requires these static methods to be present.
> 
> Then declare a variadic template function in CommonAPI
> 
> ```c++
> template<ext::Extension... extensions_t>
> ```
> 
> and somewhere inside apply a parameter pack expression to apply the features
> 
> ```c++
> (extensions_t::enableRequiredFeatures(features), ...);
> (extensions_t::enablePreferredFeautres(availableFeatures,features), ...);
> ```

Why in nabla.h?

**Comment by devshgraphicsprogramming** [comment]
> > Define a C++20 concept called `nbl::ext::Extension` at the end of `nabla.h` that requires these static methods to be present.
> > Then declare a variadic template function in CommonAPI
> > ```c++
> > template<ext::Extension... extensions_t>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and somewhere inside apply a parameter pack expression to apply the features
> > ```c++
> > (extensions_t::enableRequiredFeatures(features), ...);
> > (extensions_t::enablePreferredFeautres(availableFeatures,features), ...);
> > ```
> 
> Why in nabla.h? And why is it a c++20 thing?

Ok, if you call it `nbl::video::Extension` and only make it concern itself with video stuff (and create new ones for `core,system,asset,ui,scene` when needed), then you can stick it in `nbl/video/Extension.h`

C++20 because it would be a _concept_ and those are a C++20 feature.
