### ISSUE TITLE
Asset ImageFilters do use extents in texel dimensions incorrectly

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#436]
Ok here is a list of bugs I'm constantly encountering in the filters:
1. usage of `region->getByteOffset(offset, byteStrides)` when offset is in texel space but byteStride is always referring to blocks as the block compressed formats have custom encode/decode

same statement holds for `region->getLocalByteOffset`

:question: why didn't we find this before? note that `getByteOffset` does dot product so if offsets were always 0 we never knew you had this problem.

:exclamation: Example where it can go wrong:
`extents = 512x512x1`
`format=EF_BC1_RGBA_UNORM_BLOCK`
`byteStrides = 8,1024,131072,131072`
that means a "block" is 8 bytes NOT a "texel" that's why `offset` used in `getByteOffset` needs to be in block dimensions. 
this was ignored basically everywhere in image filters.
There is also no way to get byteStrides in texel dimensions because a formats `blockByteSize` might not always be divisible by the number of texels it holds. ( for example **ASTC_10x5**)

2. Another bug is using `core::vector3du32_SIMD`  without caution.
this is actually an SIMD vector and using dot(vec0,vec1) even if your parameter is `vector3du` the W parameter matters :smile:
I've fixed an occurrence of this bug. might exist elsewhere as well

**Comment by Erfan-Ahmadi** [comment]
3. CMatchedSizeInOutImageFilterCommon -> commonExecuteData.offsetDifference needs to be in block dimensions because it is used in `getByteOffset(offset, byteStrides)` offset calculations like [here](https://github.com/Devsh-Graphics-Programming/Nabla/blob/b2080ca73d021627ddbd97c68d73fa1626ee8a64/include/nbl/asset/filters/CCopyImageFilter.h#L68)
I already fixed this. but there is numerous places where it's used incorrectly in Convert like [here](https://github.com/Devsh-Graphics-Programming/Nabla/blob/b2080ca73d021627ddbd97c68d73fa1626ee8a64/include/nbl/asset/filters/CSwizzleAndConvertImageFilter.h#L150)
where `commonExecuteData.outByteStrides` is expected to be in "texel" dimensions to decode/encode individual texels but this is wrong again for all the reasons mentioned in **1.**

**Comment by achalpandeyy** [comment]
I believe all of this should be fixed now in #435 and being tested in https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/pull/25

**Comment by devshgraphicsprogramming** [comment]
its fixed
