### ISSUE TITLE
`CPipelineBarrierCmd` and `CWaitEventsCmd` need the definitions of `S{Buffer/Image}MemoryBarrier`

### ISSUE THREAD

**Issue by achalpandeyy** [Devsh-Graphics-Programming/Nabla#441]
Relevant commit from #345 
https://github.com/Devsh-Graphics-Programming/Nabla/pull/345/commits/ed3948b6d0ff286d9687c91e6d7e1e1c541a6926

To move `createCommandBuffers` to `IGPUCommandPool` we need access to `ICommandBuffer<>::E_LEVEL` enum but we can't include `IGPUCommandBuffer.h` in `IGPUCommandPool.h`.

Above won't compile because of circular include, gives non-sensical completely unrelated errors.

**Comment by devshgraphicsprogramming** [comment]
I also want to address and clean up this TODO: https://github.com/Devsh-Graphics-Programming/Nabla/blob/ed3948b6d0ff286d9687c91e6d7e1e1c541a6926/include/nbl/asset/ICommandBuffer.h#L24

**Comment by devshgraphicsprogramming** [comment]
Fixed in the Vk 1.3 upgrade
