### ISSUE TITLE
Bug encountered when loading a TGA file

### ISSUE THREAD

**Issue by achalpandeyy** [Devsh-Graphics-Programming/Nabla#445]
## Describe the bug

If I try to load a TGA image it seems to go into a deadlock.
Sometimes it crashes on this assert https://github.com/Devsh-Graphics-Programming/Nabla/blob/27545f29739ddf39f8cd06fa114f16815c699768/include/nbl/system/ICancellableAsyncQueueDispatcher.h#L40

## Steps to Reproduce

You can reproduce the bug on Ex61 on the branch https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/tree/tga_loader_deadlock_bug_repro

**Comment by devshgraphicsprogramming** [comment]
I fixed it in #336
