### ISSUE TITLE
Access Violation: Attempting to free empty descriptors in a descriptor pool

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [Devsh-Graphics-Programming/Nabla#710]
## Describe the bug
Create a descriptorSetLayout with a SAMPLED_IMAGE array (count=128) and ECF_PARTIALLY_BOUND_BIT flag set.
Don't update any of the bindings
Example exit will trigger DescriptorPool destructor and then `IDescriptorPool::deleteSetStorage`
The access violation happens at `std::destroy_n(getDescriptorStorage(type) + allocatedOffset, count);`
For repro run 62_Cad example on this commit: https://github.com/Devsh-Graphics-Programming/Nabla/commit/e1190279d4faea27d45717a9ee7aec615a105de9
Also, I'm not using suballocated descriptor sets, and I'm creating the descriptor pool using `createDescriptorPoolForDSLayouts`

**Comment by devshgraphicsprogramming** [comment]
btw I had the NBL enum values wrong, but I thinkg it will still crash.

**Comment by devshgraphicsprogramming** [comment]
Steps:
1. Verify that the descriptorset getting its storage deleted is has not died before (it can be mid destructor)
2. see what `type`, and what's `getDescriptorStorage(type)+allocatedOffset,count` in the Watches

My bet is that there's some garbage (non nullptr) pointers in that array despite you never updating the set.

**Comment by Fletterio** [comment]
How can I check for the former?

**Comment by devshgraphicsprogramming** [comment]
> How can I check for the former?

Visual Studio Watches window, you need to save `getDescriptorStorage(type)+allocationOffset` to some variable, then you can debug view it as an array.

**Comment by Fletterio** [comment]
Fixed, pushed straight to master

**Comment by Fletterio** [comment]
It was working for me on that commit, please confirm it does for you as well when you can @Erfan-Ahmadi and I'll close this

**Comment by Erfan-Ahmadi** [comment]
It's fixed for me as well.
