### ISSUE TITLE
Asset converter writes images to descriptor set before layout transitions, raising validation errors

### ISSUE THREAD

**Issue by Fletterio** [Devsh-Graphics-Programming/Nabla#798]
## Describe the bug
Calling `reserve` on an asset converter, passing as assets 

- An `ICPUDescriptorSet` with one descriptor binding of type `ET_SAMPLED_IMAGE` (likely same thing happens with `ET_STORAGE_IMAGE` or `ET_COMBINED_IMAGE_SAMPLER`).
- An `ICPUImageView` bound to the aforementioned binding

[will call `updateDescriptorSets`](https://github.com/Devsh-Graphics-Programming/Nabla/blob/e8f4dca1724b907826f2b9ca1f238ad114716218/src/nbl/video/utilities/CAssetConverter.cpp#L2588) when creating the corresponding `IGPUDescriptorSet`. However, the layout transition for the image from `UNDEFINED` to the expected final layout happens later [when calling `convert`](https://github.com/Devsh-Graphics-Programming/Nabla/blob/e8f4dca1724b907826f2b9ca1f238ad114716218/src/nbl/video/utilities/CAssetConverter.cpp#L3615).

## Steps to Reproduce
As an example, set up an `ICPUDescriptorSet` with a single binding of type `ET_SAMPLED_IMAGE` and use `getDescriptorInfos` to bind an `ICPUImageView` to it. Then add the descriptor set as an input asset for a converter and call `reserve` on the converter.

**Comment by devshgraphicsprogramming** [comment]
The VUID of the Validation LAyer you're getting is not about the current layout of the image, but the layout the descriptor info states

4149 and 4150 are about invalid layouts in the descriptor info.

My guess is that you're probably providing an invalid enum here: https://github.com/Devsh-Graphics-Programming/Nabla/blob/e8f4dca1724b907826f2b9ca1f238ad114716218/src/nbl/video/utilities/CAssetConverter.cpp#L1708C50-L1708C58

**Comment by devshgraphicsprogramming** [comment]
which comes from here: https://github.com/Devsh-Graphics-Programming/Nabla/blob/e8f4dca1724b907826f2b9ca1f238ad114716218/src/nbl/video/utilities/CAssetConverter.cpp#L533C82-L533C93

**Comment by devshgraphicsprogramming** [comment]
nice repro, will investigate!

**Comment by devshgraphicsprogramming** [comment]
> The VUID of the Validation LAyer you're getting is not about the current layout of the image, but the layout the descriptor info states
> 
> 4149 and 4150 are about invalid layouts in the descriptor info.
> 
> My guess is that you're probably providing an invalid enum here: https://github.com/Devsh-Graphics-Programming/Nabla/blob/e8f4dca1724b907826f2b9ca1f238ad114716218/src/nbl/video/utilities/CAssetConverter.cpp#L1708C50-L1708C58

I think I know what caused it.

its an ICPUImageVIEW not a plain image thats written into the desc-set, wrong extra parameter pack handling.
