### ISSUE TITLE
Feature full Windows

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#87]
## Description
Allow for resizes, minimizes, maximizes and rotations (mobile).

Some platforms' implementations wont allow for certain things, so capabilities must be queryable at runtime and most operations should return a bool or an enum to notify of success (please no static capability sets via inheritance).

One example is a resize, which may not be achievable to the requested size, so the actual size after the operation (same as current if nothing done) needs to be returned)

## Solution proposal
To be implemented separately in every derived window class for Win32, X11, Wayland, derivations of ForeignWindow (SDL2 which we shall use for Android)

Probably an window event callback needs to be able to be hooked up (at least to notify of an On-Resize).

## Additional context
The window functions from the IrrlichtDevice need to die
https://github.com/Crisspl/Nabla/blob/vulkan/include/IrrlichtDevice.h#L191
https://github.com/Crisspl/Nabla/blob/vulkan/include/IrrlichtDevice.h#L114

**Comment by devshgraphicsprogramming** [comment]
@Crisspl  & @sadiuk status?

**Comment by Crisspl** [comment]
Files (no file mapping yet) and window events (no rotations) have just been tested on Windows and works fine. Also IFile doesnt hold ISystem yet (@sadiuk most recent TODO is merge your smart refctd ptr changes and have it done).

**Comment by devshgraphicsprogramming** [comment]
this issue is about UI Windows, not system

**Comment by devshgraphicsprogramming** [comment]
@achalpandeyy I'll ask you for an example in the near future

**Comment by devshgraphicsprogramming** [comment]
in progress by by @deprilula28
