### ISSUE TITLE
`system` namespace

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#88]
## Description
WIP

## Solution proposal
To be done on Crisspl's `vulkan` branch

## Additional context
Stuff currently in the `io` namespace and other things which shall be in the system namespace:
~~https://github.com/Crisspl/Nabla/blob/vulkan/include/IFileSystem.h~~
https://github.com/Crisspl/Nabla/blob/vulkan/include/IFileList.h
https://github.com/Crisspl/Nabla/blob/vulkan/include/IFileArchive.h
~~ https://github.com/Crisspl/Nabla/blob/vulkan/include/ILogger.h [rewrite to use `string_view`, customize the output channel, dont make it a global etc.] ~~
https://github.com/Crisspl/Nabla/blob/vulkan/include/path.h [all functionality to be deleted]
https://github.com/Crisspl/Nabla/blob/vulkan/include/IrrlichtDevice.h#L69 [yield and sleep need to be deleted]
https://github.com/Crisspl/Nabla/blob/vulkan/include/IrrlichtDevice.h#L96 [logger and OS operator need to move]
https://github.com/Crisspl/Nabla/blob/vulkan/include/IrrlichtDevice.h#L110 [timer needs a rewrite]
https://github.com/Crisspl/Nabla/blob/vulkan/include/IOSOperator.h
~~https://github.com/Crisspl/Nabla/blob/vulkan/include/ITimer.h [timer needs a rewrite]~~

Got rewritten ~~Can stay as-is right now, but candidate for rewrite in the future (stays in the `include` directory, does not move to `nbl/system`)~~
~~https://github.com/Crisspl/Nabla/blob/vulkan/include/IReadFile.h~~
~~https://github.com/Crisspl/Nabla/blob/vulkan/include/IWriteFile.h~~

**Comment by devshgraphicsprogramming** [comment]
@Crisspl write the interfaces, @sadiuk can fill in.

**Comment by devshgraphicsprogramming** [comment]
@sadiuk what from this list has been done?

**Comment by sadiuk** [comment]
> @sadiuk what from this list has been done?

@devshgraphicsprogramming `IFilesystem` -> `ISystem`, `ILogger` tbd in the nearest future, `io::path` is removed on my fork on some branch, `ITimer` removed, `IReadFile`/`IWriteFile` -> `IFile`

**Comment by devshgraphicsprogramming** [comment]
Implemented.
