### ISSUE TITLE
Need testing of Wayland window and surface

### ISSUE THREAD

**Issue by Crisspl** [Devsh-Graphics-Programming/Nabla#96]
## Description
Need to test Wayland window and Wayland EGL surface. For it, EGL functions must be loaded from .so (test this as well if this is working correctly -- see `src/nbl/video/CEGLCaller.h`). To be able to use Wayland, one has to choose to run Wayland session while logging into Linux.
Tests should happen on **Intel GPU**, since Nvidia apparently doesnt support Wayland: https://forums.developer.nvidia.com/t/how-do-i-run-wayland-on-nvidia-geforce-rtx-2070/157870 (it's (almost?) impossible to run Wayland session on NV drivers)

## Additional context
Use my `vulkan` branch. Best to ask me about specific commit to checkout for tests (the branch is continuosly used for development). Make sure to uncomment what was commented out in this commit https://github.com/Crisspl/Nabla/commit/16b83e737cb589d95df8e7baeda6dc634406c81e and uncomment `#define _NBL_TEST_WAYLAND` in `include/nbl/core/compile_config.h`.

**Comment by devshgraphicsprogramming** [comment]
Screw wayland, sticking to XCB
